backend:
  name: git-gateway
media_folder: 'static/media'
branch: master
public_folder: '/media'
show_preview_links: true
# display_url: 
# site_url: 
collections:

 # Pages
  - label: 'Pages'
    name: 'pages'
    label_singular: 'Page'
    description: >
      Create a Page, Event, Session, or Redirect.
    folder: 'content/content'
    identifier_field: 'id'
    slug: '{{content_type}}_{{title}}'
    summary: '{{content_type}} : {{title}}'
    editor:
      preview: false
    create: true
    # filter: {field: "content_type", value: "Page"}
    fields:

      - label: 'Title'
        name: 'title'
        widget: 'string'
        hint: "Determines the URL path e.g., /[site-section]/[title]"

      - label: 'On-page title'
        name: 'page_title'
        widget: 'string'
        required: false
        hint: 'Overrides the title on the page, but does not affect the URL'

      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
        required: false
        hint: 'Simple HTML for text formatting is allowed'
    
      - label: 'Description'
        name: 'description'
        widget: 'string'
        required: false
        hint: 'Used for the meta description and other social/SEO fields'

      - label: 'Body'
        name: 'body'
        required: false
        widget: 'markdown'
      
      - label: 'Site Section'
        name: 'section'
        widget: 'select'
        required: true
        hint: "Determines the URL path e.g., /[site-section]/[title]"
        options: 
          - 'Program'
          - 'Presenters'
          - 'Students'
          - 'Travel'
          - 'About'
          - 'Redirect'

      - label: 'Content Type'
        name: 'content_type'
        widget: 'select'
        required: true
        hint: "What type of page is this?"
        options: 
          - 'Page'
          - 'Event'
          - 'Session'
          - 'Redirect'
        
      - label: 'Weight'
        name: 'weight'
        widget: 'number'
        default: 0
        valueType: 'int'

      - label: 'Redirect Link'
        name: 'link'
        widget: 'string'
        required: false
        # pattern: ['[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)', 'Must be a valid URL']
        hint: 'Use an external page or redirect to another page instead of linking directly to this page. This will appear normally in listings, but clicks will point to the redirect URL.'
               
      - label: Sidebar
        name: sidebar
        widget: list
        default: []
        required: false
        fields:
          - { label: Heading, name: heading, widget: string, required: false }
          - { label: Highlight, name: highlight, widget: boolean, required: false, hint: 'Displays this content in a box on the page' }
          - { label: 'Block content', name: block_content, widget: markdown, hint: 'Put some sidebar text here', required: false }

      - label: 'Location'
        name: 'location'
        widget: 'relation'
        collection: 'location'
        searchFields: ['title', 'venue']
        valueField: 'id'
        displayFields: ['title']
        required: false
        hint: 'Choose a location for this event. Locations need to be created before they can be added to an event.'

      - label: 'Start time'
        name: 'start'
        widget: 'datetime'
        format: 'YYYY-MM-DDTHH:mm:ssZ'
        required: false
        default: ''

      - label: 'End time'
        name: 'end'
        widget: 'datetime'
        format: 'YYYY-MM-DDTHH:mm:ssZ'
        required: false
        default: ''
    
      - label: 'RSVP Link'
        name: 'link'
        widget: 'string'
        required: false
        pattern: ['[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)', 'Must be a valid URL']
        hint: 'Enter URL if this event requires an RSVP'

      - label: 'Weight'
        name: 'weight'
        widget: 'number'
        default: 0
        valueType: 'int'

      - label: 'Registration Details'
        name: 'event_details'
        widget: 'select'
        multiple: true
        required: false
        options: 
          - 'Included in March Meeting Registration'
          - 'Open to the Public'
          - 'Limited to graduate students and early-career scientists'
          - 'Beer and wine provided'
          - 'Registration is limited and on a first come, first served basis'
          - 'Open to meeting attendees and the public'

      - label: 'Custom Registration Details'
        name: 'custom_event_details'
        widget: 'list'
        required: false
        default: []
        hint: 'Add custom details that only apply to this event or session.'
        field: { label: Detail, name: detail, widget: string }

      - label: 'Ideal for'
        name: 'ideal_for'
        widget: 'select'
        multiple: true
        required: false
        options: 
          - 'Undergrads'
          - 'Graduate Students'
          - 'Networking'
          - 'Early-Career Scientists'
          - 'Industry Professionals'
          - 'Academics'
          - 'Career Seekers'
          - 'First-time Attendees'
          - 'Educators'
          - 'Everyone'

      - label: 'Sessions'
        label_singular: 'Session'
        name: 'sessions'
        widget: 'relation'
        multiple: true
        required: false
        collection: 'pages'
        searchFields: ['title', 'content_type']
        valueField: 'id'
        displayFields: ['title']
        hint: 'If this is an Event with multiple sessions, you can associate them with this event. Select them in any order and they will be listed in order of their start times. Sessions must be created before you can add them to an event.'

#       - label: 'ID'
#         name: 'id'
#         widget: 'id'
