backend: 
  name: git-gateway
branch: master
media_folder: static/media
public_folder: /media

collections: 

  - label: Pages
    name: pages
    label_singular: Page
    folder: content/content
    create: true
    editor: 
      preview: false
      
    fields: 
      - label: Title
        name: title
        widget: string
        
      - label: Body
        name: body
        widget: markdown
      
      - label: Optional Field
        name: optional_field
        default: ''
        required: false
        widget: string
        hint: this has a default empty string
        
      - label: Required Field
        name: required_field
        default: ''
        required: true
        widget: string
        hint: this has a default empty string
        

      - label: Locations
        name: locations
        widget: list
        required: true
        default: ''
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Address, name: address, widget: string}
          
      - label: "Home Section"
        name: "sections"
        widget: "list"
        types:
          - label: "Carousel"
            name: "carousel"
            widget: object
            fields:
              - {label: Header, name: header, widget: string, default: "Image Gallery"}
              - {label: Template, name: template, widget: string, default: "carousel.html"}
              - label: Images
                name: images
                widget: list
                field: {label: Image, name: image, widget: image}
          - label: "Spotlight"
            name: "spotlight"
            widget: object
            fields:
              - {label: Header, name: header, widget: string, default: "Spotlight"}
              - {label: Template, name: template, widget: string, default: "spotlight.html"}
              - {label: Text, name: text, widget: text, default: "Hello World"}
        
#       - label: Sidebar
#         name: sidebar
#         widget: list
#         required: false
#         default: ['']
        
#         fields: 
#           - label: Heading
#             name: heading
#             required: false
#             default: ''
#             widget: string
            
#           - hint: "Displays this content in a box on the page"
#             label: Highlight
#             name: highlight
#             default: ''
#             required: false
#             widget: boolean
            
#           - hint: "Put some sidebar text here"
#             label: "Block content"
#             name: block_content
#             required: false
#             default: ''
#             widget: markdown


